# Generated by Django 4.2 on 2026-02-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolechangerequest',
            name='requested_role',
            field=models.CharField(choices=[('reader', 'Reader'), ('author', 'Author')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('author', 'Author')], default='reader', help_text='User role in the system', max_length=10),
        ),
    ]
