# Generated by Django 4.2 on 2026-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookdownload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_blob',
            field=models.BinaryField(blank=True, help_text='Binary content of uploaded book file (pdf/epub)', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='file_mime',
            field=models.CharField(blank=True, help_text='MIME type of the uploaded file', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename of uploaded book file', max_length=255, null=True),
        ),
    ]
